### ISSUE TITLE
Save File Sync to OpenRCT.net

### ISSUE THREAD

**Issue by Krutonium** [PFCKrutonium/OpenRCT2Launcher#30]
Must determine how...

**Comment by FWest98** [comment]
You can just upload the savegames to the site with the API. I can do that if I know where the files are located.

**Comment by Krutonium** [comment]
I know how to do it with the API, but I want a thread of the launcher to hang around after the game closes to upload changed maps, as well as when the launcher opens, I want to poll for changed maps...

**Comment by runelaenen** [comment]
If you need extra functions on the server, let me know. (for example: "edited after ****" so you can keep the time since the last time the player played on this machine)

**Comment by FWest98** [comment]
@PFCKrutonium I think it's better to set up a file watcher then.

**Comment by runelaenen** [comment]
@FWest98 I've got the download part working, At this moment it only checks if the file already exists, and if not it downloads the park. Should I keep implementing or is one of you going to do this?

**Comment by FWest98** [comment]
You can do that if you want of course. Just create a feature branch and a pull-request ;)

When you create a pull-request, select the right branch to target it (the feature-savegamesdownloader), so it doesn't disturb other development

**Comment by runelaenen** [comment]
@FWest98 I tried, I got it working (kind of) but I see you've refactored everything so I don't know how to implement it in your new code.
In the file is my code, if you want to see how I did it.
https://www.dropbox.com/s/ijia2c45rtk6qn1/Launcher.zip?dl=0
(but like i said, it worked, but not perfectly)

**Comment by Krutonium** [comment]
Done :D Thanks @runelaenen
