### ISSUE TITLE
When no install found, after closing options, start is enabled

### ISSUE THREAD

**Issue by FWest98** [PFCKrutonium/OpenRCT2Launcher#31]

**Comment by falki147** [comment]
Do you mean with start the "Launch OpenRCT2" button?

**Comment by FWest98** [comment]
Yes

-------- Oorspronkelijk bericht --------
Van: Florian Preinfalk notifications@github.com
Datum: 2015-02-18  12:36  (GMT+01:00)
Aan: PFCKrutonium/OpenRCT2Launcher OpenRCT2Launcher@noreply.github.com
Cc: Floris Westerman floriswesterman@msn.com
Onderwerp: Re: [OpenRCT2Launcher] When no install found, after closing options, start is enabled (#31)

Do you mean with start the "Launch OpenRCT2" button?

---

**Comment by Krutonium** [comment]
As a side note, it SHOULD enable if the person selected a directory where rct2 is installed.

**Comment by FWest98** [comment]
Of course. It should recheck I think.
