### ISSUE TITLE
Will the launcher (or game?) always require a fresh install of RCT2?

### ISSUE THREAD

**Issue by MooTorial** [PFCKrutonium/OpenRCT2Launcher#40]
This is more of a question than a bug, hopefully I'm using this right? If not, feel free to close/delete this.

**Comment by Krutonium** [comment]
The eventual goal of the OpenRCT2 Project (Wrong Repo btw, but I don't care) is to replace everything in the game with Open source equivalents. This means that eventually, RCT2 will not be needed any more (though you will still be able to use it for sounds and graphics).

**Comment by MooTorial** [comment]
Oh alright, sweet. By the way, using the latest launcher, I was getting the error where it couldn't connect to the download url. Will test again when I get home.

**Comment by Krutonium** [comment]
Okay. If you still get that error, please post a bug report.
