### ISSUE TITLE
IOException: file in use

### ISSUE THREAD

**Issue by runelaenen** [PFCKrutonium/OpenRCT2Launcher#48]
If you close the game and open the launcher within a short time, you will get this error because the old launcher is still running, trying to upload while the new launcher is trying to download the same file.
http://gyazo.com/c4dda5ef3c50e16f509fad3ff06d39c9

**Comment by Krutonium** [comment]
Hmmm... Solution would be to set a marker, like a Launcher.lock file with a time inside. If the time is above 5 minutes then ignore, otherwise do not touch.

**Comment by Krutonium** [comment]
Fixed
