### ISSUE TITLE
Need someone to test the new Extra's Menu with GOG/Vanilla installs of RCT 1 & 2.

### ISSUE THREAD

**Issue by Krutonium** [PFCKrutonium/OpenRCT2Launcher#6]
Basically, see if it works, or if it errors out.

**Comment by ThomasdenH** [comment]
The registry key "Software\fish technology group\rollercoaster tycoon setup" does not exist on my system, therefor I get a NullReferenceException. Do I need to have RCT1 installed?

**Comment by Krutonium** [comment]
Yes, you do - though the second button will let you pull the file manually.

What happens when you press the debug button?

**Comment by ThomasdenH** [comment]
I should have clarified, the Window won't open at all. It throws the error at 'Key1.GetValue("SetupPath")'

**Comment by Krutonium** [comment]
Ok, hold on, writing a fix.

**Comment by Krutonium** [comment]
In theory it won't crash on you any more.

**Comment by ThomasdenH** [comment]
It works now.

**Comment by Krutonium** [comment]
Seeing as no one has reported any further issues, i'm going to close this. Further issues can be new reports.
