### ISSUE TITLE
Ability to choose between stable/develop builds

### ISSUE THREAD

**Issue by kevinpetit** [PFCKrutonium/OpenRCT2Launcher#63]
I know it's kind of early for this, as there aren't any stable releases for OpenRCT2 yet, but it would be handy to be able to switch between the "channels" of OpenRCT2. 
I presume right now that when OpenRCT2 launches a stable release, the launcher will download that one instead of the develop versions that we are using right now. As such, we would need a toggle/setting to allow us to switch to the develop branch once again. 
That way we can test easily with the launcher in place! ;)

**Comment by Krutonium** [comment]
I have added this in, forgot to comment here. It was in 3 days ago, but I am holding off on release till there is a real Stable Build. IAC, closing :P

**Comment by kevinpetit** [comment]
Awesome, thanks :P
