### ISSUE TITLE
Enable "Cloud Saving"

### ISSUE THREAD

**Issue by Krutonium** [PFCKrutonium/OpenRCT2Launcher#7]
Basically take the Saves folder, and move it to a directory the user specifies (Like Dropbox or Mega). This will allow the user to sync saves across machines.

Goal is to make a 1 click solution for Dropbox (Reading Dropbox's Config File), with general selection for anywhere else.

**Comment by ThomasdenH** [comment]
Although it does need a publisher, not ideal for Open Source, [Google Play Saved Games](https://developers.google.com/games/services/common/concepts/savedgames) might be an option as well. It would be a way to open the same game on other devices if/when they would be supported in the future.

**Comment by Krutonium** [comment]
Android through the Google Play services SDK
iOS through the iOS SDK
C++ through the C++ SDK

Fairly sure none of these would be easy to use from a .net language on a PC.

**Comment by Krutonium** [comment]
What I am thinking is more of using a Symbolic link so that OpenRCT2 Saves into a folder on Dropbox. Set that up across multiple machines, and boom, "Cloud" saves.

**Comment by ThomasdenH** [comment]
Actually, shouldn't this be implemented in OpenRCT2 itself? Or were you thinking of customising the save path?

**Comment by Krutonium** [comment]
All I am doing is customizing the save path. In theory once you make this change, even the original RCT2 should save to Dropbox.

**Comment by Krutonium** [comment]
You can check out the code on the buttons under extra to see what I did.
