### ISSUE TITLE
Dutch Localisation: Use Metric instead of Imperial

### ISSUE THREAD

**Issue by francoism90** [PFCKrutonium/OpenRCT2Launcher#72]
See title. :)

Could the launcher also search in this path for the RCT2 game?
C:\Program Files (x86)\GOG Games\RollerCoaster Tycoon 2 Triple Thrill Pack

Thanks.

**Comment by runelaenen** [comment]
Where does the launcher use metric/imperial values?

**Comment by francoism90** [comment]
When using the launcher, go to Options and on the first tab. ;)
Not in Windows atm. if needed I can provide a screenshot.

**Comment by francoism90** [comment]
See screenshots:
https://drive.google.com/file/d/0BzfSuVpNNRzqMEJzeXo5T0VUZWc/view?usp=sharing
