### ISSUE TITLE
OpenRCT2 Launcher says it can't connect to internet even though I have internet connection

### ISSUE THREAD

**Issue by gofirst2220** [PFCKrutonium/OpenRCT2Launcher#74]
see title. On my Surface Pro 3 I can't download OpenRCT2 though the launcher because it can't connect to internet. I'm on Windows 10 Pro. I have internet connection through Wi-Fi network.

**Comment by runelaenen** [comment]
Is google reachable? It pings Google.com to see if an internet connection is available.

**Comment by gofirst2220** [comment]
It's reachable. However, I can access google from Microsoft Edge, Chrome, Firefox, etc. I don't know why the launcher wouldn't connect to the internet.

**Comment by runelaenen** [comment]
Does it say it doesn't work, or does it really not work. The massage should only restrict the fancy images, the updater itself should still work.

**Comment by gofirst2220** [comment]
The Updater didn't download OpenRCT2 on it's own. It just says "Downloading" at the click of "Launch OpenRCT2" (does nothing) and at the launcher main Splash (white splash) it says "offline mode: no internet connection found."

**Comment by Krutonium** [comment]
This will no longer be an issue in the new launcher.
