### ISSUE TITLE
[REQUEST] Add launcher status

### ISSUE THREAD

**Issue by Enzemo** [PFCKrutonium/OpenRCT2Launcher#76]
Hey,

So currently when the launcher opens up and starts updating, it just greys out the buttons.

I was thinking that if it's possible to add a status display or progress bar, it would help identify problems, and would reassure new players that their launcher does actually work.

An example would be "Status: Updating - 53% 5.3 MB/s". Or even just something as simple as "Status: Updating" "Status: Could not connect to server" "Status: Ready to launch - Build XXXXXXX" etc

Many thanks

**Comment by Krutonium** [comment]
Check latest Beta.
