### ISSUE TITLE
.net website security certificate expired, launcher broken 

### ISSUE THREAD

**Issue by jensj12** [PFCKrutonium/OpenRCT2Launcher#84]
I can no longer update the game with the launcher now the .net website has an expired security certificate (chaning to stable channel kept me on the outdated development build I had installed). Please update the launcher to use another website instead.

**Comment by runelaenen** [comment]
It's not the website's certificates that are expired, but the certificate used to sign the launcher itself. It used to be free for open source projects, but they started charging 50 euros which is something I'm not really willing to pay. 
You can use the alternative launcher found on the OpenRCT2.com website.

**Comment by Krutonium** [comment]
LRFLEW's launcher is replacing this launcher, check the stickies on Reddit.com/r/rct
