### ISSUE TITLE
Add a portable checkbox.

### ISSUE THREAD

**Issue by thegreatestminer** [PFCKrutonium/OpenRCT2Launcher#85]
Basically it would be nice to have a checkbox and when checked, it adds --user-path-data %cd% to the command-line for OpenRCT2, thus allowing it to be fully portable. (I think)

**Comment by Krutonium** [comment]
This launcher is no longer maintained... You would be better off poking LRFLEW's launcher.

**Comment by thegreatestminer** [comment]
Oh, I didn't know that. Sorry.
