### ISSUE TITLE
what is win32:malware-gen?

### ISSUE THREAD

**Issue by jamtraks** [PFCKrutonium/OpenRCT2Launcher#86]
when i try to run the launcher and at the end of it's download, my avg anti-virus software is detecting "win32:malware-gen", and blocking openrct2 from opening. What is win32:malware-gen? is this something that is always detected or attached to the openrct2 download for everyone, or is this being generated or injected by something else on my computer such as a virus that only i have??? i'd really like to know if this file is truly harmless and something that everyone downloads or if it is coming from something else...
and if this is always attached to the openrct2 download what is it exactly and why is it there?

**Comment by jamtraks** [comment]
anyway... i was told that this is nothing to worry about, so i've uninstalled avg anti-virus and i am now able to play openrct2. I don't seem to have any virus or problems at the moment. Thanks

**Comment by runelaenen** [comment]
You shouldn't use this launcher anymore, but download the one on https://openrct2.org/downloads

While it's safe to use (in terms of malware or virusses - AVG is indeed in the wrong there), we can't guarantee that this launcher still works correctly. Some of the services (like CoasterCloud) have been turned off when we switched from openrct.net to openrct2.com about 2 years ago.
