### ISSUE TITLE
Launcher fails to launch game Mac OS Big Sur 11.6.1

### ISSUE THREAD

**Issue by jamesixgun** [PFCKrutonium/OpenRCT2Launcher#88]
When I attempt to launch the game via the launcher, it fails silently and leaves the following bunch of comments in the Console. This happens with the Release or the Develop version. The launcher downloads the current version of either just fine, but just doesn't start them. 
If I navigate to ~Library/Application Support/OpenRCT2/bin and try to launch the game, I get essentially the same messages in an error window.

`Process:               OpenRCT2 [16994]
Path:                  /Users/USER/Library/Application Support/OpenRCT2/*/OpenRCT2.app/Contents/MacOS/OpenRCT2
Identifier:            OpenRCT2
Version:               0.3.5.1 (0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           OpenRCT2 [16968]
User ID:               501

Date/Time:             2021-11-22 17:13:51.105 -0600
OS Version:            macOS 11.6.1 (20G224)
Report Version:        12
Bridge OS Version:     6.0 (19P548)
Anonymous UUID:        B727C3AE-5650-E948-4583-6F668A6BCD4D

Sleep/Wake UUID:       367B10C8-AAB3-40E8-84AD-0316E5215A98

Time Awake Since Boot: 440000 seconds
Time Since Wake:       640 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: 80896B32-9EB1-3A10-A7C5-449B15305DE2
Library not loaded: @executable_path/../Frameworks/libduktape.2.dylib
  Referenced from: /Users/USER/Library/Application Support/OpenRCT2/*/OpenRCT2.app/Contents/MacOS/OpenRCT2
  Reason: no suitable image found.  Did find:
	/Users/james/Library/Application Support/OpenRCT2/bin/OpenRCT2.app/Contents/MacOS/../Frameworks/libduktape.2.dylib: file too short
	/Users/james/Library/Application Support/OpenRCT2/bin/OpenRCT2.app/Contents/MacOS/../Frameworks/libduktape.2.dylib: file too short

Binary Images:
       0x10cb17000 -        0x10cc92fff +io.openrct2.OpenRCT2 (0.3.5.1 - 0) <FB793892-5AE1-3C83-BB48-FE3758D7FECB> /Users/USER/Library/Application Support/OpenRCT2/*/OpenRCT2.app/Contents/MacOS/OpenRCT2
       0x10cd90000 -        0x10d3e7fff +libopenrct2.dylib (0) <1B83F1B4-3F57-36C8-9893-50A1B7D0697A> /Users/USER/Library/Application Support/OpenRCT2/*/OpenRCT2.app/Contents/Frameworks/libopenrct2.dylib
       0x10df21000 -        0x10df80fff +libssl.1.1.dylib (0) <C784F0CC-D80D-3FE2-B4F7-48C50023D87D> /Users/USER/Library/Application Support/OpenRCT2/*/OpenRCT2.app/Contents/Frameworks/libssl.1.1.dylib
       0x10dfb4000 -        0x10e197fff +libcrypto.1.1.dylib (0) <307DBFBB-94B4-3D78-9274-85DDEE0028E5> /Users/USER/Library/Application Support/OpenRCT2/*/OpenRCT2.app/Contents/Frameworks/libcrypto.1.1.dylib
       0x114470000 -        0x11450bfff  dyld (852.2) <14C5D17F-5032-37A2-9CD8-F437EB4A3992> /usr/lib/dyld
    0x7fff32ff9000 -     0x7fff3305ffff  libcurl.4.dylib (121.101.1) <517F6BB3-5752-3B40-9107-E35C627A1E43> /usr/lib/libcurl.4.dylib
    0x7fff3502f000 -     0x7fff35032fff  com.apple.Cocoa (6.11 - 23) <E8E14342-DDF9-3351-B93D-8DEDBA5CAABA> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff6bbc9000 -     0x7fff6bbd8fff  com.apple.opengl (18.5.9 - 18.5.9) <2A421CC5-4D60-339C-9772-3AC991232BD8> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
`

Any thoughts? 

I'm glad to work with anyone to help solve this. I'm not a total novice with Macs or code, but I don't know much.

**Comment by jamesixgun** [comment]
By the way, I'm able to launch the Release and Develop versions if I download and launch them myself, after allowing permissions via the Security & Privacy panel in System Preferences.

**Comment by Krutonium** [comment]
It looks to me like it downloaded a build missing libducktape - But aside from that you should be aware that this launcher is defunct.

**Comment by jamesixgun** [comment]
Thanks! 
this has happened with every build for many months, and happens with both develop and release. 
And since the launcher is defunct, I won’t bother you any further. Apologies!

**Comment by Krutonium** [comment]
No worries - That said, I believe LRFLEW has a replacement that should work as advertised. https://github.com/LRFLEW/OpenRCT2Launcher
